- Gemfile.lock
- country_select.gemspec
This is meant to be a temporary fix until countries v0.10.1 is released and can be integrated into country_select.
> Triage poor performance by preventing usage of countries gem v0.10.0

- lib/country_select/tag_helper.rb
This is a small performance improvement, we don't need to re-instantiate a county object if already looked up at line 70
```
if country = ISO3166::Country.new(code_or_name)
```
PS: ```ISO3166::Country.new``` creates new instances every time:
````
irb(main):004:0> ISO3166::Country.new('IT').object_id
=> 70160945975800
irb(main):005:0> ISO3166::Country.new('IT').object_id
=> 70160945381520
````
> Don't re-instantiate the country object if not required

- lib/country_select/tag_helper.rb
- spec/country_select_spec.rb
This patch checks whether any of the priority countries options' `value`s were `selected` (instead of whether any of the priority countries `alpha2`s' were `selected`.)  This prevents priority country from being marked as selected twice when using a custom array-style formatter.
> Mark priority countries as selected only once

- README.md
It appears that bundler may not always install the latest gem version if you leave the version unspecified. This doesn't address the root cause in #155, but hopefully prevents confusion in the future.
Closes #155
> Explicitly specify latest version in README

- country_select.gemspec
RubyForge was close more than 5 years ago from what I can tell.
> Remove deprecated rubyforge_project  from gemspec

- lib/country_select/formats.rb
I sometimes have this error : 
```
NoMethodError: undefined method `[]' for nil:NilClass
File /app/vendor/bundle/ruby/2.5.0/gems/country_select-4.0.0/lib/country_select/formats.rb line 5 in block in <module:CountrySelect>
```
I don't know why, but it happens that the translations are not correctly loaded and **country.translations** is **nil**
> Safely dig into country translations

- README.md
This changes the badge to the stefanpenner/country_select one, but only the `master` branch.
> README: Update CI badge to point to default branch only

- lib/country_select/formats.rb
- spec/country_select_spec.rb
This fixes an issue inadvertently introduced in version 5.0.0 by https://github.com/stefanpenner/country_select/pull/173.
In locales like `en-US` or `de-CH`, with version 5.0.0 we started seeing the ISO names instead of the common names in our country dropdowns. This PR fixes the default format so that fallbacks work correctly, while preserving the handling of nil/missing translations.
> Fix i18n fallback in country translations

- .travis.yml
This is a workaround to avoid YAML issue re: the float 3.0 turning into the string "3".
(By making all of them strings, we perhaps don't need to explain this YAML quirk.)
> CI: Turn YAML floats into String

- README.md
- lib/country_select.rb
- lib/country_select/defaults.rb
- lib/country_select/tag_helper.rb
- lib/country_select_without_sort_alphabetical.rb
- spec/country_select_spec.rb
This allows configuring defaults, for example excluding certain countries app-wide.
Closes #183
> Add ability to configure defaults

- Gemfile.lock
- country_select.gemspec
- gemfiles/actionpack.edge.gemfile.lock
- gemfiles/actionpack5.2.gemfile.lock
- gemfiles/actionpack6.0.gemfile.lock
- gemfiles/actionpack6.1.gemfile.lock
v4.0.0 was just released, dropping support for Ruby versions older than 2.5 and bumping i18n-data to the latest version
> Update countries gem to 4.0+.

- README.md
- country_select.gemspec
- lib/country_select/formats.rb
- spec/country_select_spec.rb
Latest release [4.2.0](https://github.com/countries/countries/releases/tag/v4.2.0) of gem includes some deprecations.
This PR updates the dependency to 4.2 and replaces references to deprecated `#name `method with` #iso_short_name`
Also updates references to the gem's repo, that has since moved.
> Update 'countries' dependency to 4.2

- README.md
Some readme links still had the old org name
> Update README.md - Update Org-name

- .github/workflows/build.yml
- country_select.gemspec
> Drop support for EOLd Ruby 2.5 and 2.6

- lib/country_select/country_select_helper.rb
The syntax change for defining priority countries happened on 2.0, released on 2014-08-10, so I think we should deprecate it.
> Add deprecation warning for old priority country syntax

- README.md
- lib/country_select/defaults.rb
- lib/country_select/tag_helper.rb
- spec/country_select_spec.rb
@scudco 
I've been thinking about #194 , and came up with another possibility:
```ruby
country_select :user, :country_code, only: %w(CH AT DE), sort_provided: false
country_select :user, :country_code, priority_countries: %w(CH AT DE), sort_provided: false
```
That is, adding a `sort_provided` option that controls if the list of countries is locale-sorted or we use the order of the `only` and `priority_countries` array. 
~The default behaviour is unchanged from the current version, this just adds the new option to allow preserving the sort order as inputted, and is a pretty small code change.~
This adds the new option and is a small change, but it changes the default behaviour for `priority_countries` to sorting the list, so that both `priority_countries` and `only` have the same sorting …
> Allow option to preserve the sort order as inputted in the `only` array of countries

- lib/country_select/tag_helper.rb
- spec/country_select_spec.rb
Fix: Using priority countries with the sort_provided: false, should still sort the rest of the countries by name.
See issue described in #209
> Fix priority country sorting bug

- .github/workflows/codeql-analysis.yml
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> Update CodeQL to V2

- .github/workflows/test.yml
- gemfiles/actionpack-7.1.gemfile
- gemfiles/actionpack-7.1.gemfile.lock
- lib/country_select/tag_helper.rb
A recent Rails Edge commit (https://github.com/rails/rails/commit/77f3fc118a211c973bc3ca0b720dcba932474f89) moves the Form Options helper into select rendering classes. This is a breaking change for `country_select`. 
This PR adds support for the changes, and it has been tested with all of the versions of Rails that `country_select` supports.
If the approach I've used is not what you prefer, perhaps it will spark some additional ideas for addressing the issue.
> Adding support for Rails 7.1 after recent Form Options helper changes

- Gemfile.lock
- lib/country_select/tag_helper.rb
Addresses when country name is `nil`, was getting same error described here: https://github.com/countries/country_select/issues/207
> Fix when country name is nil.

- Gemfile.lock
- lib/country_select/tag_helper.rb
- spec/country_select_spec.rb
Thank you so much for creating and maintaining this wonderful library.
I recently encountered an issue when using it with the locale set to `ja`, where country names weren’t sorting as expected.
After some investigation, I discovered that the sorting logic uses `I18n.transliterate`, which—as noted in the [documentation](https://www.rubydoc.info/gems/activesupport/2.3.17/I18n.transliterate)—converts non-Latin characters into a `'?'`. This means that Japanese country names are turned into a series of question marks (e.g., `"???"`), which disrupts the sort order.
To address this, I’ve updated the code so that if the transliteration result contains a `'?'`, the original string is used instead for sorting. Since country names in Latin script normally wouldn’t include a `'?'`, this approach …
> fix: Improve sorting for non-Latin country names
